export const PROJECT_FETCH_REQ="PROJECT_FETCH_REQ"
export const PROJECT_FETCH_SUC="PROJECT_FETCH_SUC"
export const PROJECT_FETCH_FAIL="PROJECT_FETCH_FAIL"

export const PROJECT_DELETE_REQ="PROJECT_DELETE_REQ"
export const PROJECT_DELETE_SUC="PROJECT_DELETE_SUC"
export const PROJECT_DELETE_FAIL="PROJECT_DELETE_FAIL"