export const PROJECT_FETCH_REQ = "PROJECT_FETCH_REQ";
export const PROJECT_FETCH_SUC = "PROJECT_FETCH_SUC";
export const PROJECT_FETCH_FAIL = "PROJECT_FETCH_FAIL";

export const PROJECT_DELETE_REQ = "PROJECT_DELETE_REQ";
export const PROJECT_DELETE_SUC = "PROJECT_DELETE_SUC";
export const PROJECT_DELETE_FAIL = "PROJECT_DELETE_FAIL";

export const PROJECT_CREATE_REQ = "PROJECT_CREATE_REQ";
export const PROJECT_CREATE_SUC = "PROJECT_CREATE_SUC";
export const PROJECT_CREATE_FAIL = "PROJECT_CREATE_FAIL";
export const PROJECT_CREATE_RESET = "PROJECT_CREATE_RESET";

export const PROJECT_DETAIL_REQ = "PROJECT_DETAIL_REQ";
export const PROJECT_DETAIL_SUC = "PROJECT_DETAIL_SUC";
export const PROJECT_DETAIL_FAIL = "PROJECT_DETAIL_FAIL";
export const PROJECT_DETAIL_RESET = "PROJECT_DETAIL_RESET";

export const PROJECT_UPDATE_REQ = "PROJECT_UPDATE_REQ";
export const PROJECT_UPDATE_SUC = "PROJECT_UPDATE_SUC";
export const PROJECT_UPDATE_FAIL = "PROJECT_UPDATE_FAIL";
export const PROJECT_UPDATE_RESET = "PROJECT_UPDATE_RESET";
