export const SKILLS_FETCH_REQ = "SKILLS_FETCH_REQ";
export const SKILLS_FETCH_SUC = "SKILLS_FETCH_SUC";
export const SKILLS_FETCH_FAIL = "SKILLS_FETCH_FAIL";

export const SKILLS_DELETE_REQ = "SKILLS_DELETE_REQ";
export const SKILLS_DELETE_SUC = "SKILLS_DELETE_SUC";
export const SKILLS_DELETE_FAIL = "SKILLS_DELETE_FAIL";
