export const SKILLS_FETCH_REQ = "SKILLS_FETCH_REQ";
export const SKILLS_FETCH_SUC = "SKILLS_FETCH_SUC";
export const SKILLS_FETCH_FAIL = "SKILLS_FETCH_FAIL";

export const SKILLS_DELETE_REQ = "SKILLS_DELETE_REQ";
export const SKILLS_DELETE_SUC = "SKILLS_DELETE_SUC";
export const SKILLS_DELETE_FAIL = "SKILLS_DELETE_FAIL";

export const SKILL_CREATE_REQ = "SKILL_CREATE_REQ";
export const SKILL_CREATE_SUC = "SKILL_CREATE_SUC";
export const SKILL_CREATE_FAIL = "SKILL_CREATE_FAIL";
export const SKILL_CREATE_RESET = "SKILL_CREATE_RESET";

export const SKILL_DETAIL_REQ = "SKILL_DETAIL_REQ";
export const SKILL_DETAIL_SUC = "SKILL_DETAIL_SUC";
export const SKILL_DETAIL_FAIL = "SKILL_DETAIL_FAIL";
export const SKILL_DETAIL_RESET = "SKILL_DETAIL_RESET";

export const SKILL_UPDATE_REQ = "SKILL_UPDATE_REQ";
export const SKILL_UPDATE_SUC = "SKILL_UPDATE_SUC";
export const SKILL_UPDATE_FAIL = "SKILL_UPDATE_FAIL";
export const SKILL_UPDATE_RESET = "SKILL_UPDATE_RESET";
